version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=homework'
      - 'POSTGRES_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres'